---
- hosts: all
  
  become: yes
  tasks:


  - name: update 
    shell: "sudo yum update"

  # Install Docker
  # --
  # 
  - name: install docker 
    yum:
      name: 
        - docker
      update_cache: yes

  - name: add userpermissions
    shell: "usermod -aG docker {{ lookup('env','USER') }}"

  # Installs Docker SDK
  # --
  # 
  - name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
  
  - name: install python sdk
    become_user: "{{ lookup('env','USER') }}"
    pip:
      name:
        - docker
        - docker-compose