---
- hosts: front

  become: true
  vars:
    default_container_image: "varesinatalia/realia:latest"
  tasks:
    - name: make sure port 80 is free
      shell: "sudo systemctl disable apache2 && sudo systemctl stop apache2"

    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
      ignore_errors: yes

    - name: Remove Stoped docker containers
      shell: |
         docker rm $(docker ps -a -q);
      when: docker_info.containers != 0
      ignore_errors: yes

    - name: Get details of all images
      docker_host_info:
        images: yes
        verbose_output: yes
      register: image_info
      ignore_errors: yes

    - name: Remove all images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ image_info.images | map(attribute='Id') | list }}"
      ignore_errors: yes

    
    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: run frontend docker containers
      shell: "docker run -d -p 80:80 --name digitalwebtier varesinatalia/realia:latest"


