stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  image: maven:3.6.3-jdk-11-slim
  script:
    - ls 
    - cd back/ProyectInt/
    - echo "Start building App"
    - mvn clean install -Dspring.profiles.active=$SPRING_ACTIVE_PROFILE && mvn package -B -e -Dspring.profiles.active=$SPRING_ACTIVE_PROFILE
  artifacts:
    expire_in: 1 hour
    paths:
      - back/ProyectInt/target/*.jar

test:
  stage: test
  needs: [build]
  image: maven:3-jdk-11-slim
  script: 
  - cd back/ProyectInt/
  - "mvn test"
  artifacts:
    paths:
      - back/ProyectInt/target/*.jar

variables:
  DOCKER_REGISTRY: 145504712931.dkr.ecr.us-west-2.amazonaws.com
  AWS_DEFAULT_REGION: us-west-2
  REPOSITORY_NAME: digitalbooking10
publish:
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - cd back/
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$REPOSITORY_NAME:latest . 
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$REPOSITORY_NAME:latest
