stages:
  - build
  - test
  - publish

build:
  stage: build
  image: node
  script: 
    - echo "Start building App"
    - cd front/reserva-hoteles/
    - npm install
    - CI=false npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - front/reserva-hoteles/build
      - front/reserva-hoteles/node_modules/

.test:
  stage: test
  needs: [build]
  image: node
  script:
    - echo "Testing App"
    - cd front/reserva-hoteles/
    - npm install
    - CI=true npm test --passWithNoTests
    - echo "Test successfully!"

publish:
  stage: publish
  #needs: [test]
  image: docker:latest
  services: 
    - name: docker:19.03.8-dind
  before_script:
    - cd front/
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE"/realia .
    - docker push "$CI_REGISTRY_IMAGE"/realia
    - echo "Registry image:" $CI_REGISTRY_IMAGE/realia

