stages:
  - build
  - test
  - deploy

image: alpine

build_front:
  stage: build
  script:
    - echo "This job builds something."

test_front:
  stage: test
  needs: [build_front]
  script:
    - echo "This job tests something."

deploy_front:
  stage: deploy
  needs: [test_front]
  script:
    - echo "This job deploys something."
