
#back
  packages:
  - docker.io
runcmd:
  - sudo yum update -y
  - sudo yum install -y docker
  - sudo systemctl start docker
  - sudo systemctl enable docker
  - docker pull varesinatalia/realia:latest
  - docker run -p 80:80 --name digitalwebtier varesinatalia/realia:latest