version: '2'
services:
  mysql:
    image: 'mysql:latest'
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=g10Booking
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=g10Booking
    ports:
      - '3307:3306'
