-- MySQL Script generated by MySQL Workbench
-- Fri Jun  3 18:23:37 2022
-- Model: proyecto_integrador Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_integrador` ;
USE `proyecto_integrador` ;

-- -----------------------------------------------------
-- Table `proyecto_integrador`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`cities` (
  `id_city` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_city`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_integrador`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`categories` (
  `id_category` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `url_image` VARCHAR(200) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_integrador`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`products` (
  `id_product` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `cancellation_policies` VARCHAR(255) NULL,
  `cities_id_city` INT NOT NULL,
  `categories_id_category` INT NOT NULL,
  `health_hygiene` VARCHAR(255) NULL,
  PRIMARY KEY (`id_product`, `cities_id_city`, `categories_id_category`),
  INDEX `fk_products_cities_idx` (`cities_id_city` ASC),
  INDEX `fk_products_categories_idx` (`categories_id_category` ASC),
  CONSTRAINT `fk_products_cities`
    FOREIGN KEY (`cities_id_city`)
    REFERENCES `proyecto_integrador`.`cities` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_categories`
    FOREIGN KEY (`categories_id_category`)
    REFERENCES `proyecto_integrador`.`categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_integrador`.`features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`features` (
  `id_features` INT NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_features`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_integrador`.`products_has_features`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`products_has_features` (
  `products_id_product` INT NOT NULL,
  `features_id_feature` INT NOT NULL,
  PRIMARY KEY (`products_id_product`, `features_id_feature`),
  INDEX `fk_products_has_features_features_idx` (`features_id_feature` ASC),
  INDEX `fk_products_has_features_products_idx` (`products_id_product` ASC),
  CONSTRAINT `fk_products_has_features_products`
    FOREIGN KEY (`products_id_product`)
    REFERENCES `proyecto_integrador`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_features_features`
    FOREIGN KEY (`features_id_feature`)
    REFERENCES `proyecto_integrador`.`features` (`id_features`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_integrador`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`images` (
  `id_image` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `url` VARCHAR(200) NULL,
  `products_id_product` INT NOT NULL,
  INDEX `fk_images_products_idx` (`products_id_product` ASC),
  CONSTRAINT `fk_images_products`
    FOREIGN KEY (`products_id_product`)
    REFERENCES `proyecto_integrador`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_integrador`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`scores` (
  `id_score` INT NOT NULL,
  `product_score` INT NULL,
  `products_id_product` INT NOT NULL,
  PRIMARY KEY (`id_score`),
  INDEX `fk_scores_products_idx` (`products_id_product` ASC),
  CONSTRAINT `fk_scores_products`
    FOREIGN KEY (`products_id_product`)
    REFERENCES `proyecto_integrador`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_integrador`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`roles` (
  `id_rol` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_integrador`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`users` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `roles_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_user`, `roles_id_rol`),
  INDEX `fk_users_roles_idx` (`roles_id_rol` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id_rol`)
    REFERENCES `proyecto_integrador`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_integrador`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_integrador`.`reservations` (
  `id_reservation` BIGINT NOT NULL,
  `checkin_date` DATE NOT NULL,
  `checkout_date` DATE NOT NULL,
  `additional_info` VARCHAR(200) NULL,
  `products_id_product` INT NOT NULL,
  `users_id_user` INT NOT NULL,
  PRIMARY KEY (`id_reservation`, `users_id_user`),
  UNIQUE INDEX `id_reservation_UNIQUE` (`id_reservation` ASC),
  INDEX `fk_reservations_products_idx` (`products_id_product` ASC),
  INDEX `fk_reservations_users_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_reservations_products`
    FOREIGN KEY (`products_id_product`)
    REFERENCES `proyecto_integrador`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_users`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `proyecto_integrador`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
